<?php
### =============================================================
### Mastop InfoDigital - Paixão por Internet
### =============================================================
### Arquivo de Configuração do Módulo
### =============================================================
### Developer: Fernando Santos (topet05), fernando@mastop.com.br
### Copyright: Mastop InfoDigital © 2003-2007
### -------------------------------------------------------------
### www.mastop.com.br
### =============================================================
###
### =============================================================

require_once __DIR__ . '/preloads/autoloader.php';

$moduleDirName      = basename(__DIR__);
$moduleDirNameUpper = mb_strtoupper($moduleDirName);

require_once XOOPS_ROOT_PATH . '/modules/' . MGO_MOD_DIR . '/include/funcoes.inc.php';

// Dados do Módulo
$modversion['version']             = '1.04';
$modversion['module_status']       = 'RC 1';
$modversion['release_date']        = '2017/06/22';
$modversion['name']                = MGO_MOD_NOME;
$modversion['author']              = 'Fernando Santos (aka topet05)';
$modversion['description']         = MGO_MOD_DESC;
$modversion['credits']             = 'Mastop InfoDigital - www.mastop.com.br';
$modversion['help']                = 'page=help';
$modversion['license']             = 'GNU GPL 2.0';
$modversion['license_url']         = 'www.gnu.org/licenses/gpl-2.0.html/';
$modversion['official']            = 0; //1 indicates supported by XOOPS Dev Team, 0 means 3rd party supported
$modversion['image']               = 'assets/images/logoModule.png';
$modversion['dirname']             = basename(__DIR__);
$modversion['modicons16']          = 'assets/images/icons/16';
$modversion['modicons32']          = 'assets/images/icons/32';
$modversion['module_website_url']  = 'www.xoops.org/';
$modversion['module_website_name'] = 'XOOPS';
$modversion['min_php']             = '5.5';
$modversion['min_xoops']           = '2.5.10';
$modversion['min_admin']           = '1.2';
$modversion['min_db']              = ['mysql' => '5.5'];

// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Arquivo Sql (Deve conter o dump de todas as tabelas do módulo)
// Todas as tabelas devem estar sem o prefixo!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tabelas criadas pelo Arquivo sql (sem prefixo poha!)
$modversion['tables'][0] = MGO_MOD_TABELA0;
$modversion['tables'][1] = MGO_MOD_TABELA1;

// Itens da Administração
$modversion['hasAdmin']   = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu']  = 'admin/menu.php';

$modversion['blocks'][1]['file']        = MGO_MOD_BLOCO1_FILE;
$modversion['blocks'][1]['name']        = MGO_MOD_BLOCO1;
$modversion['blocks'][1]['description'] = MGO_MOD_BLOCO1_DESC;
$modversion['blocks'][1]['show_func']   = MGO_MOD_BLOCO1_SHOW;
$modversion['blocks'][1]['edit_func']   = MGO_MOD_BLOCO1_EDIT;
$modversion['blocks'][1]['options']     = '0|200|1|1|6|333333|FFFFFF|50';
$modversion['blocks'][1]['template']    = MGO_MOD_BLOCO1_TEMPLATE;

// ------------------- Help files ------------------- //
$modversion['helpsection'] = [
    ['name' => MI_MGO_OVERVIEW, 'link' => 'page=help'],
    ['name' => MI_MGO_DISCLAIMER, 'link' => 'page=disclaimer'],
    ['name' => MI_MGO_LICENSE, 'link' => 'page=license'],
    ['name' => MI_MGO_SUPPORT, 'link' => 'page=support'],
];

// Menu
$modversion['hasMain'] = 1;

// Busca
$modversion['hasSearch'] = 0;

// Configurações (Para as preferências do módulo)
$imgcatHandler                          = xoops_getHandler('imagecategory');
$catlist                                = array_flip($imgcatHandler->getList([], 'imgcat_read', 1));

$modversion['config'][] = [
    'name'        => 'mgo_des_img',
    'title'       => 'MGO_MOD_DSTAC_IMG',
    'description' => 'MGO_MOD_DSTAC_IMG_DES',
    'formtype'    => 'select_multi',
    'valuetype'   => 'array',
    'options'     => $catlist,
];
/**
 * Make Sample button visible?
 */
$modversion['config'][] = [
    'name'        => 'displaySampleButton',
    'title'       => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_SAMPLE_BUTTON',
    'description' => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_SAMPLE_BUTTON_DESC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => 1,
];

/**
 * Show Developer Tools?
 */
$modversion['config'][] = [
    'name'        => 'displayDeveloperTools',
    'title'       => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_DEV_TOOLS',
    'description' => 'CO_' . $moduleDirNameUpper . '_' . 'SHOW_DEV_TOOLS_DESC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => 0,
];
