<?php
### =============================================================
### Mastop InfoDigital - Paixão por Internet
### =============================================================
### Arquivo de Configuração do Módulo
### =============================================================
### Developer: Fernando Santos (topet05), fernando@mastop.com.br
### Copyright: Mastop InfoDigital © 2003-2007
### -------------------------------------------------------------
### www.mastop.com.br
### =============================================================
### $Id: xoops_version.php 10472 2012-12-19 10:35:10Z beckmi $
### =============================================================
include_once XOOPS_ROOT_PATH . "/modules/" . MGO_MOD_DIR . "/include/funcoes.inc.php";
// Dados do Módulo
$modversion['name'] = MGO_MOD_NOME;
$modversion['version'] = 1.02;
$modversion['author'] = 'Fernando Santos (aka topet05)';
$modversion['description'] = MGO_MOD_DESC;
$modversion['credits'] = "Mastop InfoDigital - www.mastop.com.br";
$modversion['help'] = 'page=help';
$modversion['license'] = 'GNU GPL 2.0';
$modversion['license_url'] = "www.gnu.org/licenses/gpl-2.0.html/";
$modversion['official'] = 0;
$modversion['image'] = "images/mgo2_logo.gif";
$modversion['dirname'] = MGO_MOD_DIR;

$modversion['dirmoduleadmin'] = '/Frameworks/moduleclasses/moduleadmin';
$modversion['icons16'] = '../../Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = '../../Frameworks/moduleclasses/icons/32';

//about
$modversion['release_date'] = '2012/12/17';
$modversion["module_website_url"] = "www.xoops.org/";
$modversion["module_website_name"] = "XOOPS";
$modversion["module_status"] = "Final";
$modversion['min_php'] = '5.2';
$modversion['min_xoops'] = "2.5.5";
$modversion['min_admin'] = '1.1';
$modversion['min_db'] = array('mysql' => '5.0.7', 'mysqli' => '5.0.7');

// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Arquivo Sql (Deve conter o dump de todas as tabelas do módulo)
// Todas as tabelas devem estar sem o prefixo!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tabelas criadas pelo Arquivo sql (sem prefixo poha!)
$modversion['tables'][0] = MGO_MOD_TABELA0;
$modversion['tables'][1] = MGO_MOD_TABELA1;

// Itens da Administração
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['blocks'][1]['file'] = MGO_MOD_BLOCO1_FILE;
$modversion['blocks'][1]['name'] = MGO_MOD_BLOCO1;
$modversion['blocks'][1]['description'] = MGO_MOD_BLOCO1_DESC;
$modversion['blocks'][1]['show_func'] = MGO_MOD_BLOCO1_SHOW;
$modversion['blocks'][1]['edit_func'] = MGO_MOD_BLOCO1_EDIT;
$modversion['blocks'][1]['options'] = '0|200|1|1|6|333333|FFFFFF|50';
$modversion['blocks'][1]['template'] = MGO_MOD_BLOCO1_TEMPLATE;

// Menu
$modversion['hasMain'] = 1;

// Busca
$modversion['hasSearch'] = 0;

// Configurações (Para as preferências do módulo)
$imgcat_handler =& xoops_gethandler('imagecategory');
$catlist =& array_flip($imgcat_handler->getList(array(), 'imgcat_read', 1));
$modversion['config'][1]['name'] = 'mgo_des_img';
$modversion['config'][1]['title'] = 'MGO_MOD_DSTAC_IMG';
$modversion['config'][1]['description'] = 'MGO_MOD_DSTAC_IMG_DES';
$modversion['config'][1]['formtype'] = 'select_multi';
$modversion['config'][1]['valuetype'] = 'array';
$modversion['config'][1]['options'] = $catlist;